### ISSUE TITLE
Extremely slow load times

### ISSUE THREAD

**Issue by ajthemacboy** [Mar6M/MinecraftAvatarQuery#16]
Hi, not sure if this is an issue on my end or the result of something in the code.

I have a website for our Minecraft server (it's WIP.. haha). The address is:

https://rubix-ajthemacboy.rhcloud.com/

You can see the widget is on the right side once you scroll down. It sometimes never loads, and sometimes loads extremely slowly. The host I use, Openshift, is pretty fast. I can't imagine that it's the problem. I simply put the widget in an iframe. Could this be why it's so slow to load?

Thanks for any help you can offer.

**Comment by Mar6M** [comment]
Hi,
Perhaps the background images are too big? Large images usually take a lot of time to load (depending on your Internet connection).

**Comment by ajthemacboy** [comment]
I meant that the script itself was loading slowly, not the website in general.

But either way it seems to have picked up in speed now, only 1 or 2 seconds. My host must have been a little overloaded at the time. Sorry to bother you! :)

**Comment by Mar6M** [comment]
No problem :)

In that case yes, it probably was an issue on your end with the host or there was something going on @McLive's API.
